### ISSUE TITLE
Able to add candidates with same email

### ISSUE THREAD

**Issue by sarthakmalik0810** [abhpd-team/OEP-Frontend#27]
Also, if candidate Id is found to be duplicate, there is no alert. Consider adding let's say a snackbar. Consider using material-ui.

**Comment by abhpd** [comment]
Currently, we're just keeping the IDs unique.

@19BCS1114 What you think? Should we allow the cases where two candidates can have the same email or fix to check for duplicates?

**Comment by 19BCS1114** [comment]
always room for improvement @abhpd

**Comment by abhpd** [comment]
@sarthakmalik0810 Okay so we will not have duplicate emails and IDs. it should give an alert if a user is trying to add a duplicate entry.

**Comment by abhpd** [comment]
We already have a check in place for unique IDs here: https://github.com/abhpd-team/OEP-Frontend/blob/main/src/components/classes/class.jsx#L87

We just need to check for email as well.
